name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# permissions:
#   contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      checkov_failed: ${{ steps.set_checkov_status.outputs.checkov_failed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov (IaC security scan)
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - name: Set Checkov Status
        id: set_checkov_status
        run: |
          if [ "${{ steps.checkov.outcome }}" = "failure" ]; then
            echo "checkov_failed=true" >> $GITHUB_OUTPUT
          else
            echo "checkov_failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      # - name: Terraform Destroy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform destroy -auto-approve

  notify-slack:
    needs: terraform
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set Slack Message and Title
        run: |
          if [[ "${{ needs.terraform.result }}" == "success" ]]; then
            echo "SLACK_COLOR=#36a64f" >> $GITHUB_ENV
            echo "SLACK_TITLE=Terraform CI Succeeded" >> $GITHUB_ENV
            echo "SLACK_MESSAGE=All steps in the Terraform CI workflow have passed successfully! :tada:" >> $GITHUB_ENV
          elif [[ "${{ needs.terraform.outputs.checkov_failed }}" == "true" ]]; then
            echo "SLACK_COLOR=#FF0000" >> $GITHUB_ENV
            echo "SLACK_TITLE=Checkov Failed" >> $GITHUB_ENV
            echo "SLACK_MESSAGE=Checkov failed: Please review the IaC security scan results." >> $GITHUB_ENV
          else
            echo "SLACK_COLOR=#FF0000" >> $GITHUB_ENV
            echo "SLACK_TITLE=Terraform CI Failed" >> $GITHUB_ENV
            echo "SLACK_MESSAGE=A step in the Terraform CI workflow has failed. Please check the GitHub Actions logs for details." >> $GITHUB_ENV
          fi

      - name: Notify Slack of Result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ env.SLACK_COLOR }}
          SLACK_TITLE: ${{ env.SLACK_TITLE }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}